# Generated by Django 5.0.6 on 2024-06-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_post_comment_profile_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
